version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:7.17.7
    build:
      context: .
      dockerfile: ES.Dockerfile
      cache_from:
        - elasticsearch:7.17.7
        - type=local,src=path/to/cache
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  es-data:
    driver: local

networks:
  elastic: