CREATE DATABASE IF NOT EXISTS `openjob`;

CREATE USER IF NOT EXISTS 'openjob'@'%' IDENTIFIED BY '123456';
GRANT SELECT,UPDATE,INSERT ON `openjob`.* TO 'openjob'@'%';
flush privileges;

use `openjob`;
CREATE TABLE IF NOT EXISTS `Job` (
  `JobId` INT PRIMARY KEY AUTO_INCREMENT,
  `DistrictId` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `CompanyName` VARCHAR(255) NOT NULL,
  `StartDate` DATETIME,
  `EndDate` DATETIME,
  `SalaryFrom` DECIMAL(10,2),
  `SalaryTo` DECIMAL(10,2),
  `Lat` DECIMAL(10,6),
  `Lon` DECIMAL(10,6),
  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `JobCategory` (
  `JobCategoryId` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `JobCategoryJob` (
  `JobCategoryId` INT NOT NULL,
  `JobId` INT NOT NULL,
  `TypeId` INT NOT NULL,
  PRIMARY KEY (`JobCategoryId`, `JobId`,`TypeId`),
  KEY '' (JobCategoryId, JobId, TypeId)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;